# Use uma imagem base do Python
FROM python:3.12

# Instale o git
RUN apt-get update && apt-get install -y git

# Defina o diretório de trabalho
WORKDIR /app

# Clone o repositório do GitHub
RUN git clone https://github.com/ArthurRufi/ProjetoFinalLibras.git

# Instale as dependências
RUN pip install --no-cache-dir -r requirements.txt

# Exponha a porta que o Django usa
EXPOSE 8000

# Comando para iniciar o servidor Django
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
